FROM node:22-alpine

WORKDIR /app

# Copiar solo package.json y package-lock.json para instalar dependencias primero
COPY package*.json ./
RUN npm install

# Copiar el entrypoint y darle permisos
COPY .docker/backend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copiar el resto de los archivos del proyecto
COPY . .

# Instalar Prisma CLI globalmente para desarrollo
RUN npm install -g prisma

# Exponer el puerto de desarrollo
EXPOSE 3000

# Setear el entrypoint
ENTRYPOINT ["/entrypoint.sh"]

# Comando para ejecutar el servidor y aplicar migraciones
CMD ["sh", "-c", "npx prisma migrate dev && npm run dev"]
