FROM node:22-alpine

WORKDIR /app

# Copiar solo package.json y package-lock.json para instalar dependencias primero
COPY package*.json ./
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Instalar Prisma CLI globalmente para desarrollo
RUN npm install -g prisma

# Exponer el puerto de desarrollo
EXPOSE 3000

# Comando para ejecutar el servidor en desarrollo
CMD ["npm", "run", "dev"]
